const CONFIG={API_URL:"PASTE_APPS_SCRIPT_WEB_APP_URL_HERE"};let db={orders:[],technicians:[],customers:[]};
const $=x=>document.getElementById(x), money=n=>"Rp "+Number(n||0).toLocaleString("id-ID");
function toast(x){$("toast").textContent=x;$("toast").style.display="block";setTimeout(()=>$("toast").style.display="none",2200)}
function nav(p){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$(p).classList.add("active");render()}
document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>nav(b.dataset.page));
async function api(action,data={}){if(CONFIG.API_URL.startsWith("PASTE_"))return mock(action,data);let r=await fetch(CONFIG.API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,...data})});return r.json()}
function mock(a,p){if(a==="list")return Promise.resolve(db);if(a==="createOrder"){let o={id:"ORD-"+Date.now().toString().slice(-6),createdAt:new Date().toISOString(),status:"Baru",...p};db.orders.unshift(o);db.customers.push({id:"CUS-"+Date.now(),name:p.customerName,phone:p.customerPhone,address:p.address});return Promise.resolve({ok:true})}if(a==="createTechnician"){db.technicians.push({id:"TEC-"+Date.now(),createdAt:new Date().toISOString(),status:"Aktif",...p});return Promise.resolve({ok:true})}if(a==="updateOrder"){let o=db.orders.find(x=>x.id===p.id);if(o){o.status=p.status;o.technicianId=p.technicianId||o.technicianId;o.finalPrice=p.finalPrice??o.finalPrice;o.techFee=p.techFee??o.techFee}return Promise.resolve({ok:true})}}
function esc(x=""){return String(x).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function load(){db=await api("list");render()}
function render(){
let active=document.querySelector(".page.active")?.id,total=db.orders.length,activeN=db.orders.filter(o=>!["Selesai","Dibatalkan"].includes(o.status)).length,done=db.orders.filter(o=>o.status==="Selesai"),revenue=done.reduce((s,o)=>s+Number(o.finalPrice||o.price||0),0),fees=done.reduce((s,o)=>s+Number(o.techFee||0),0);
$("stats").innerHTML=`<div class=card><small>Total Order</small><strong>${total}</strong></div><div class=card><small>Order Aktif</small><strong>${activeN}</strong></div><div class=card><small>Order Selesai</small><strong>${done.length}</strong></div><div class=card><small>Teknisi Aktif</small><strong>${db.technicians.filter(t=>t.status!=="Nonaktif").length}</strong></div>`;
$("recent").innerHTML=tableOrders(db.orders.slice(0,8));
renderOrders();renderTech();renderCustomers();renderFinance(revenue,fees);
if(active==="dashboard"){}
}
function tableOrders(rows){if(!rows.length)return "<p class=muted>Belum ada data.</p>";return `<table class=table><tr><th>Order</th><th>Customer</th><th>Service</th><th>Teknisi</th><th>Nilai</th><th>Status</th><th></th></tr>${rows.map(o=>{let t=db.technicians.find(t=>t.id===o.technicianId);return `<tr><td><b>${esc(o.id)}</b><div class=muted>${new Date(o.createdAt).toLocaleString("id-ID")}</div></td><td>${esc(o.customerName)}<div class=muted>${esc(o.customerPhone)}</div></td><td>${esc(o.service)}</td><td>${t?esc(t.name):"Belum ditentukan"}</td><td>${money(o.finalPrice||o.price)}</td><td><span class=badge>${esc(o.status)}</span></td><td><button class=btn onclick="detail('${o.id}')">Detail</button></td></tr>`}).join("")}</table>`}
function renderOrders(){let q=($("search")?.value||"").toLowerCase(),f=$("filter")?.value||"";let rows=db.orders.filter(o=>(!q||`${o.customerName} ${o.customerPhone} ${o.service}`.toLowerCase().includes(q))&&(!f||o.status===f));$("orderList").innerHTML=tableOrders(rows)}
function renderTech(){ $("technician").innerHTML='<option value="">Belum ditentukan</option>'+db.technicians.map(t=>`<option value="${t.id}">${esc(t.name)} — ${esc(t.area)}</option>`).join("");$("techList").innerHTML=db.technicians.length?`<table class=table><tr><th>Teknisi</th><th>Area</th><th>Keahlian</th><th>Alat</th><th>Kendaraan</th><th>Status</th></tr>${db.technicians.map(t=>`<tr><td><b>${esc(t.name)}</b><div class=muted>${esc(t.phone)}</div></td><td>${esc(t.area)}</td><td>${esc(t.skills)}</td><td>${esc(t.tools)}</td><td>${esc(t.vehicle)}</td><td><span class=badge>${esc(t.status||"Aktif")}</span></td></tr>`).join("")}</table>`:"<p class=muted>Belum ada teknisi.</p>"}
function renderCustomers(){let m=new Map();db.customers.forEach(c=>m.set(c.phone,c));let r=[...m.values()];$("custList").innerHTML=r.length?`<table class=table><tr><th>Nama</th><th>WhatsApp</th><th>Alamat</th></tr>${r.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.phone)}</td><td>${esc(c.address)}</td></tr>`).join("")}</table>`:"<p class=muted>Belum ada customer.</p>"}
function renderFinance(rev,fees){$("financeStats").innerHTML=`<div class=card><small>Omzet Selesai</small><strong>${money(rev)}</strong></div><div class=card><small>Total Fee Teknisi</small><strong>${money(fees)}</strong></div><div class=card><small>Margin Platform</small><strong>${money(rev-fees)}</strong></div><div class=card><small>Order Selesai</small><strong>${db.orders.filter(o=>o.status==="Selesai").length}</strong></div>`;$("financeList").innerHTML=tableOrders(db.orders.filter(o=>o.status==="Selesai"))}
function openOrder(){$("orderForm").reset();$("orderModal").classList.add("show");renderTech()}function openTech(){$("techForm").reset();$("techModal").classList.add("show")}function closeModal(id){$(id).classList.remove("show")}
$("search").oninput=renderOrders;$("filter").onchange=renderOrders;
$("orderForm").onsubmit=async e=>{e.preventDefault();let p={customerName:$("name").value,customerPhone:$("phone").value,address:$("address").value,service:$("service").value,priority:$("priority").value,complaint:$("complaint").value,price:Number($("price").value),techFee:Number($("techFee").value),technicianId:$("technician").value,status:"Baru"};let r=await api("createOrder",p);if(r.ok){closeModal("orderModal");toast("Order dibuat");load()}}
$("techForm").onsubmit=async e=>{e.preventDefault();let p={name:$("tn").value,phone:$("tp").value,area:$("ta").value,skills:$("ts").value,tools:$("tools").value,vehicle:$("vehicle").value,payment:$("pay").value,status:"Aktif"};let r=await api("createTechnician",p);if(r.ok){closeModal("techModal");toast("Teknisi ditambahkan");load()}}
async function detail(id){let o=db.orders.find(x=>x.id===id),t=db.technicians.find(x=>x.id===o.technicianId);$("detail").innerHTML=`<h2>${esc(o.id)}</h2><p><b>${esc(o.customerName)}</b> · ${esc(o.customerPhone)}</p><p>${esc(o.address)}</p><p><b>${esc(o.service)}</b> — ${esc(o.complaint)}</p><hr><label>Status<select id=dstatus>${["Baru","Ditawarkan","Diterima","On Progress","Selesai","Dibatalkan"].map(s=>`<option ${s===o.status?"selected":""}>${s}</option>`).join("")}</select></label><label>Teknisi<select id=dtech><option value="">Belum ditentukan</option>${db.technicians.map(x=>`<option value="${x.id}" ${x.id===o.technicianId?"selected":""}>${esc(x.name)} — ${esc(x.area)}</option>`).join("")}</select></label><div class=two><label>Harga Final<input id=dfinal type=number value="${o.finalPrice??o.price??0}"></label><label>Fee Teknisi<input id=dfee type=number value="${o.techFee??0}"></label></div><p>Teknisi: <b>${t?esc(t.name):"Belum ada"}</b></p><button class="primary wide" onclick="saveDetail('${id}')">Simpan Perubahan</button>`;$("detailModal").classList.add("show")}
async function saveDetail(id){let r=await api("updateOrder",{id,status:$("dstatus").value,technicianId:$("dtech").value,finalPrice:Number($("dfinal").value),techFee:Number($("dfee").value)});if(r.ok){closeModal("detailModal");toast("Order diperbarui");load()}}
load();